# Generated by Django 3.1.7 on 2021-04-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='transfer_to',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_with',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
