# Generated by Django 3.1.7 on 2021-04-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210410_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('credited', 'credited'), ('debited', 'debited'), ('pending', 'pending')], default=None, max_length=50),
        ),
    ]
