# Generated by Django 3.1.7 on 2021-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210410_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
