# Generated by Django 3.1.7 on 2021-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210410_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='requests',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
