# Generated by Django 3.1.7 on 2021-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210411_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('credited', 'credited'), ('debited', 'debited')], default=None, max_length=50),
        ),
    ]
