# Generated by Django 3.1.7 on 2021-04-18 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_customer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='curr_login',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
